jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true

  analyze:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: git fetch --unshallow
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin -o:'ethan-epperson' -k:'ethan-epperson_training-code-week4.0' -d:sonar.login='fc4025fdfb1d9417f909c8911891903639b92e49' -d:sonar.host.url='https://sonarcloud.io'
          dotnet build
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --loger trx
          dotnet sonarscanner end -d:sonar.login='fc4025fdfb1d9417f909c8911891903639b92e49'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #package:
  #deploy:

name: cibuild

on: push



#person:
#  firstName: "string" # string
# lastName: 100 # number
#  middleName: true # boolean
#  alias: # collections
#   - "dotnet" # the dash shows it is a collection
#   - "lead"
#   - subAlias: #you could do this but you probably shouldn't